config_basename: finetune
tmp_dir: /opt/ml/code
pretrained_model_dir: /opt/ml/pretrained_model
freeze_pretrained: True
training:
  epochs: 100
  loss: CrossEntropy
  batch_size: 16
  opt:
    opt_name: adam
  lr: 0.003
  num_workers: 4
  shuffle: True
  tensorboard_logdir: /opt/ml/model
dataset:
  basedir: /opt/ml/input/data/training/
  indexes:
    - ../datasets_indexes/ACM_mirum_tempo.json
    - ../datasets_indexes/giantsteps-tempo-dataset-master.json
    - ../datasets_indexes/hainsworth.json
  sr: 44100
  random_excerpt: True
  num_samples: 600000
  start_sample: 0
  downmix_to_mono: True
  rseed: 2345
  splits:
    train: 0.8
    val: 0.2
    rseed: 42
  use_augmentations: False
  augmentations:
    - pitch_shifting
  aug_params:
    pitch_shifting:
      cent_min: -400
      cent_max: 400
frontend:
  use_augmentations: False
docker:
  outdir: /opt/ml/model



