config_basename: train
training:
  epochs: 10
  loss: l1_ratio
  batch_size: 16
  opt:
    opt_name: adam
  lr: 0.001
  num_workers: 4
  shuffle: True
  checkpoint: False
  tensorboard_logdir: /opt/ml/model
dataset:
  basedir: /opt/ml/input/data/training/
  indexes:
    - ../datasets_indexes/magnatagatune.json
  sr: 44100
  random_excerpt: True
  num_samples: 600000
  start_sample: 0
  downmix_to_mono: True
  rseed: 2345
  splits:
    train: 0.8
    val: 0.2
    rseed: 42
  use_augmentations: True
  augmentations:
#    - pitch_shifting
    - timestretch
  aug_params:
    pitch_shifting:
      cent_min: -400
      cent_max: 400
    timestretch:
      rate_min: 0.8
      rate_max: 1.2
model:
  model_name: TCN
  mode: regression
  num_filters: 16
  dropout: 0.0
  add_proj_head: False
  proj_head_dim: 32
frontend:
  sr: 44100
  n_fft: 2048
  hop_length: 441
  n_mels: 81
  f_min: 30
  f_max: 17000
  power: 1
  use_augmentations: True
  augmentations:
    - volume
    - polarity_inversion
    - gaussian_noise
    - freq_masking
  aug_params:
    timestretch:
      rate_min: 0.8
      rate_max: 1.2
    volume:
      gain_min: -5.0
      gain_max: 5.0
    polarity_inversion:
      prob: 0.5
    gaussian_noise:
      std_min: 0.0
      std_max: 0.7
    freq_masking:
      mask_ratio_max: 0.2
docker:
  outdir: /opt/ml/model
  checkpoint_dir: /opt/ml/checkpoints


